name: UnitTest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Unit Test
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet.
      run: dotnet build --configuration Release AdventOfCode/AdventOfCode.sln
    - name: Run unit tests.
      run: dotnet test AdventOfCode/AdventOfCode.sln
